//
//  ArticleWorker.swift
//  yaaulyanenkovPW5
//
//  Created by Ярослав Ульяненков on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ArticleWorker {
    
    func downloadArticles(request: Article.Fetch.Request, completition: @escaping (Article.Fetch.Response?) -> ()){
        guard let url = request.urlBuilder() else {
            return
        }
        var result: Article.Fetch.Response? = nil
        URLSession.shared.dataTask(with: url) { data, response, error in
            if let error = error {
                print(error)
                return
            }
            if let data = data {
                result = try? JSONDecoder().decode(Article.Fetch.Response.self, from: data)
                result?.passTheRequestId()
                completition(result)
            }
        }.resume()
    }
}
