//
//  ArticleInteractor.swift
//  yaaulyanenkovPW5
//
//  Created by Ярослав Ульяненков on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticleBusinessLogic
{
  func doSomething(request: Article.Fetch.Request)
}

protocol ArticleDataStore
{
  //var name: String { get set }
}

class ArticleInteractor: ArticleBusinessLogic, ArticleDataStore
{
  var presenter: ArticlePresentationLogic?
  var worker: ArticleWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Article.Fetch.Request)
  {
    worker = ArticleWorker()
    worker?.doSomeWork()
    
    let response = Article.Fetch.Response()
    presenter?.presentSomething(response: response)
  }
}
