//
//  ArticleRouter.swift
//  yaaulyanenkovPW5
//
//  Created by Ярослав Ульяненков on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import WebKit

@objc protocol ArticleRoutingLogic
{
    func showArticle(source: ArticleViewController, articleURL: URL?)
}

protocol ArticleDataPassing
{
  var dataStore: ArticleDataStore? { get }
}

class ArticleRouter: NSObject, ArticleRoutingLogic, ArticleDataPassing
{
  weak var viewController: ArticleViewController?
  var dataStore: ArticleDataStore?

  // MARK: Navigation
  
  func showArticle(source: ArticleViewController, articleURL: URL?)
  {
      guard let url = articleURL else { return }
      let controller = WebViewController()
      controller.url = url
      source.show(controller, sender: nil)
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ArticleDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
