//
//  ArticleModels.swift
//  yaaulyanenkovPW5
//
//  Created by Ярослав Ульяненков on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Article
{
    enum Fetch
    {
        struct Request
        {
            var rubrikId = 4
            var pageSize: Int
            var pageIndex: Int
            
            func urlBuilder() -> URL? {
                return URL(string: "https://news.myseldon.com/api/Section?rubricId=\(rubrikId)&pageSize=\(pageSize)&pageIndex=\(pageIndex)")
            }
        }
        
        struct Response: Codable
        {
            let newsTotalCount: Int?
            var news: [ArticleModel]?
            var requestId: String?
            
            mutating func passTheRequestId() {
                for i in 0..<(news?.count ?? 0) {
                    news?[i].requestId = requestId
                }
            }
        }
        
        struct ArticleModel: Codable
        {
            let newsId: Int?
            let img: ImageContainer?
            let title: String?
            let announce: String?
            var requestId: String?
            var articleUrl: URL? {
                let requestId = requestId ?? ""
                let newsId = newsId ?? 0
                return URL(string: "https://news.myseldon.com/ru/news/index/\(newsId)?requestId=\(requestId)")
            }
            
        }
        
        struct ImageContainer: Codable {
            let url: URL?
        }
    }
}
