//
//  ArticlePresenter.swift
//  yaaulyanenkovPW5
//
//  Created by Ярослав Ульяненков on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticlePresentationLogic
{
    func presentArticles(response: Article.Fetch.Response)
}

class ArticlePresenter: ArticlePresentationLogic
{
  weak var viewController: ArticleDisplayLogic?
  
  func presentArticles(response: Article.Fetch.Response)
  {
      let viewModels = response.news ?? []
      viewController?.displayArticles(viewModels: viewModels)
  }
}
